// Profile page actions
export const GET_USER = 'GET_USER';
export const GET_DEFAULT_USER = 'GET_DEFAULT_USER';
export const REGISTRATION_USER = 'REGISTRATION_USER';
export const REGISTRATION_DEFAULT_USER = 'REGISTRATION_DEFAULT_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const DEFAULT_CHECK_TOKEN = 'DEFAULT_CHECK_TOKEN';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_USER_BY_SAGA = 'EDIT_USER_BY_SAGA';
export const ADD_PHOTO_URL = 'ADD_PHOTO_URL';

// Authorization/Registration
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// Employers page actions
export const CREATE_EMPLOYER = 'CREATE_EMPLOYER';
export const GET_EMPLOYERS = 'GET_EMPLOYERS';
export const ADD_EMPLOYERS = 'ADD_EMPLOYERS';
export const ADD_EMPLOYER = 'ADD_EMPLOYER';
export const CHANGE_ACTIVE_EMP_BTN = 'CHANGE_ACTIVE_EMP_BTN';
export const ADD_LOCAL_EMPLOYERS = 'ADD_LOCAL_EMPLOYERS';
export const CHANGE_FILTER_RATING = 'CHANGE_FILTER_RATING';
export const CLEAR_EMPLOYERS = 'CLEAR_EMPLOYERS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const CHANGE_STATE = 'CHANGE_STATE';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_EMPLOYER = 'DELETE_EMPLOYER';

// Loader
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const CHECK_TOKEN_SHOW_LOADER = 'CHECK_TOKEN_SHOW_LOADER';
export const CHECK_TOKEN_HIDE_LOADER = 'CHECK_TOKEN_HIDE_LOADER';

// Errors
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

// Rating Types
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const ADD_ALL_USERS = 'ADD_ALL_USERS';
export const FILTER_USERS = 'FILTER_USERS';
export const CHANGE_RATING = 'CHANGE_RATING';
export const DEFAULT_CHANGE_RATING = 'DEFAULT_CHANGE_RATING';

// SHOP ACTION_TYPES
export const GET_ALL_SHOP_ITEMS = 'GET_ALL_ITEMS';
export const GET_DEFAULT_SHOP_ALL_ITEMS = 'GET_DEFAULT_ALL_ITEMS';
export const ADD_SHOP_ITEMS = 'ADD_ITEMS';
export const ADD_DEFAULT_SHOP_ITEMS = 'ADD_DEFAULT_ITEMS';
export const DELETE_DEFAULT_ITEM_SHOP = 'DELETE_DEFAULT_ITEM_SHOP';
export const BUY_DEFAULT_ITEM_SHOP = 'BUY_DEFAULT_ITEM_SHOP';

// ORDER TYPES
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';
